# Generated by Django 4.2.5 on 2024-05-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationColorDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_association', models.CharField()),
                ('class_id', models.IntegerField()),
                ('color', models.CharField(max_length=7)),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('is3d', models.BooleanField()),
                ('model', models.CharField()),
                ('dr_method', models.CharField()),
                ('project_name', models.CharField()),
                ('class_name', models.CharField(max_length=50)),
                ('cluster_id', models.BigIntegerField()),
                ('file_reference', models.CharField()),
                ('thumbnail_reference', models.CharField()),
            ],
        ),
    ]
